apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
  generation: 1
  name: httpbin
#  namespace: default
spec:
  gateways:
  - httpbin-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /headers
    - uri:
        prefix: /delay/
    - uri:
        exact: /
    route:
    - destination:
        host: httpbin
        subset: v1
        port:
          number: 8080
      weight: 100
