---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: httpbin_mapping
      prefix: /headers
      service: httpbin.default:8000
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  httpbin_shadow_mapping
      prefix: /headers
      service: demo.k8s-pcconsultants.de:80
      shadow: true
spec:
  ports:
  - name: httpbin
    port: 8000
    targetPort: 8000
