apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    chart: tracing-1.0.6
    heritage: Tiller
    release: release-name
  name: zipkin
  namespace: istio-system
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: TracingService
      name: tracing
      service: zipkin.istio-system:9411
      driver: zipkin
spec:
  ports:
  - name: http
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: jaeger
  sessionAffinity: None
