apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "website-disable-rule"
spec:
  host: "website.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
