apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checkversion
spec:
  match: destination.labels["app"] == "website"
  actions:
  - handler: whitelist.listchecker
    instances:
    - appversion.listentry
