apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "demo3"
spec:
  host: "*.demo3.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
