apiVersion: config.istio.io/v1alpha2
kind: listchecker
metadata:
  name: whitelist
spec:
  # providerUrl: ordinarily black and white lists are maintained
  # externally and fetched asynchronously using the providerUrl.
#  overrides: ["v1", "v2"]  # overrides provide a static list
  overrides: ["website-version-1", "website-version-2"] # intended to test website app
  blacklist: false
