apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "website-tls"
spec:
  targets:
  - name: "website"
  peers:
  - mtls: 
      mode: PERMISSIVE
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "website-tls"
spec:
  host: website.default.svc.cluster.local
  subsets:
  - name: version-1
    labels:
      version: website-version-1
  - name: version-2
    labels:
      version: website-version-2
  - name: version-3
    labels:
      version: website-version-3
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
